name: Manual Matrix Test

on:
  workflow_dispatch:
    inputs:
      test_function:
        description: '테스트할 함수 이름 (test_tensorflow_model)'
        required: true
        default: 'test_tensorflow_model'

jobs:
  matrix-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9, 3.10]

    name: ${{ matrix.os }} / Python ${{ matrix.python-version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run specific test function
      run: |
        echo "실행할 함수: ${{ github.event.inputs.test_function }}"
        echo "
        import pytest
        pytest.main(['-k', '${{ github.event.inputs.test_function }}'])
        " > run_test.py
        python run_test.py
