name: Update README with livetime release

on:
  repository_dispatch:
    types: [livetime-release]

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Emotion-Prediction
        uses: actions/checkout@v3

      - name: Update README.md
        run: |
          echo "## submodule release" > README.md
          echo "[![Livetime Release](https://img.shields.io/github/v/release/honeyJo0215/livetime?label=livetime)](https://github.com/honeyJo0215/livetime/releases)" >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "auto update: livetime newest release" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/honeyJo0215/Emotion-Prediction.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
